employees:
   path: /employees
   controller: App\Controller\EmployeesController::getEmployees
customers:
   path: /customers
   controller: App\Controller\CustomersController::getCustomers
offices:
   path: /offices
   controller: App\Controller\OfficesController::getOffices
Orderdetails:
   path: /orderDetails
   controller: App\Controller\OrderdetailsController::getOrderDetails
orders:
   path: /orders
   controller: App\Controller\OrdersController::getOrders
payments:
   path: /payments
   controller: App\Controller\PaymentsController::getPayments
productLines:
   path: /productLines
   controller: App\Controller\ProductlinesController::getProductLines
products:
   path: /products
   controller: App\Controller\ProductsController::getProducts
   
